server:
  port: 8045

spring:
  datasource:
    url: jdbc:postgresql://dpg-cqcm4riju9rs7393qvd0-a.oregon-postgres.render.com:5432/adoptify_authdb
    username: sebastian
    password: r6JTUz2moYagP458znlcuwRe8Gj3PhFt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: PROTECTORA-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://nocountrydeploy.onrender.com/eureka
